const types = {
    alert: {
        "ADD_ALERT": "ADD_ALERT",
        "DELETE_ALERT": "DELETE_ALERT"
    },
    modal: {
        "TOGGLE_MODAL": "TOGGLE_MODAL"
    },
    login: {
        "LOGIN_USER": "LOGIN_USER",
        "REGISTER_USER": "REGISTER_USER",
        "FORGOT_PASSWORD": "FORGOT_PASSWORD",
        "RESET_PASSWORD": "RESET_PASSWORD",
        "LOGOUT_USER": "LOGOUT",
        "SAVE_USER_INFO": "SAVE_USER_INFO",
        "SWITCH_LOADING_STATUS": "SWITCH_LOADING_STATUS"
    },
    profile: {
        "GET_USER_PROFILE": "GET_USER_PROFILE",
        "UPDATE_USER_PROFILE": "UPDATE_USER_PROFILE",
        "UPDATE_USER_PROFILE_PIC": "UPDATE_USER_PROFILE_PIC",
        "UPDATE_DAY_OPEN_CLOSE_STATUS": "UPDATE_DAY_OPEN_CLOSE_STATUS",
        "SWITCH_PROFILE_LOADER": "SWITCH_PROFILE_LOADER"
    },
    category: {
        "GET_CATEGORIES": "GET_CATEGORIES",
        "SAVE_CATEGORY": "SAVE_CATEGORY",
        "GET_CATEGORY_BY_ID": "GET_CATEGORY_BY_ID",
        "UPDATE_CATEGORY": "UPDATE_CATEGORY",
        "DELETE_CATEGORY": "DELETE_CATEGORY",
        "SWITCH_CATEGORY_LOADER": "SWITCH_CATEGORY_LOADER"
    },
    subCategory: {
        "GET_SUB_CATEGORIES": "GET_SUB_CATEGORIES",
        "GET_SUB_CATEGORIES_BY_CATEGORY_ID": "GET_SUB_CATEGORIES_BY_CATEGORY_ID",
        "SAVE_SUB_CATEGORY": "SAVE_SUB_CATEGORY",
        "GET_SUB_CATEGORY_BY_ID": "GET_SUB_CATEGORY_BY_ID",
        "UPDATE_SUB_CATEGORY": "UPDATE_SUB_CATEGORY",
        "DELETE_SUB_CATEGORY": "DELETE_SUB_CATEGORY",
        "SWITCH_SUB_CATEGORY_LOADER": "SWITCH_SUB_CATEGORY_LOADER"
    },
    menu: {
        "GET_MENU": "GET_MENU",
        "SAVE_MENU": "SAVE_MENU",
        "GET_MENU_BY_ID": "GET_MENU_BY_ID",
        "UPDATE_MENU": "UPDATE_MENU",
        "UPDATE_MENU_PIC": "UPDATE_MENU_PIC",
        "DELETE_MENU": "DELETE_MENU",
        "SWITCH_MENU_LOADER": "SWITCH_MENU_LOADER"
    },
    tables: {
        "GET_TABLES_STATUS": "GET_TABLES_STATUS",
        "ADD_TABLE_COVER": "ADD_TABLE_COVER",
        "SWITCH_TABLES_LOADER": "SWITCH_TABLES_LOADER"
    },
    mostOrdered: {
        "GET_MOST_ORDERED": "GET_MOST_ORDERED",
        "SWITCH_MOST_ORDERED": "SWITCH_MOST_ORDERED"
    },
    orders: {
        "GET_ORDER_ITEM_LIST": "GET_ORDER_ITEM_LIST",
        "SAVE_ORDER_ITEM": "SAVE_ORDER_ITEM",
        "UPDATE_QUANTITY": "UPDATE_QUANTITY",
        "COMPLETE_ORDER": "COMPLETE_ORDER",
        "VOID_ORDER": "VOID_ORDER",
        "SWITCH_ORDER_LOADER": "SWITCH_ORDER_LOADER"
    },
    customers: {
        "GET_CUSTOMER_BY_ID": "GET_CUSTOMER_BY_ID",
        "SEARCH_CUSTOMER": "SEARCH_CUSTOMER",
        "SAVE_CUSTOMER": "SAVE_CUSTOMER",
        "CLEAR_CUSTOMER": "CLEAR_CUSTOMER",
        "SWITCH_CUSTOMER_LOADER": "SWITCH_CUSTOMER_LOADER"
    },
    openCloseDay: {
        "OPEN_CLOSE_DAY": "OPEN_CLOSE_DAY",
        "SWITCH_DAY_LOADER": "SWITCH_DAY_LOADER"
    },
    settleBill: {
        "BIND_VENDORS": "BIND_VENDORS",
        "BIND_PAYMENT_MODES": "BIND_PAYMENT_MODES",
        "SETTLE_BILL": "SETTLE_BILL",
        "GET_SETTLED_BILL": "GET_SETTLED_BILL",
        "SWITCH_BILL_SETTLEMENT_LOADER": "SWITCH_BILL_SETTLEMENT_LOADER"
    }
};

export default types;