export default {
    "tableNumberLabel": 'Table Number: ',
    "coverLabel": 'Cover',
    "billNumberLabel": 'Bill Number:',
    "categoryLabel": 'Category',
    "itemCodeLabel": 'Item Code',
    "measuringUnitLabel": 'Measuring Unit',
    "pricingLabel": 'Pricing',
    "gstLabel": 'GST(%)',
    "dailySalesReportTitle": 'Daily Sale Report By Payment Modes',
    "isVegLabel": 'Is Veg',
    "descriptionLabel": 'Description',
    "viewPricingLinkLabel": 'View Price',
    "addCoverTitle": 'Add Cover',
    "settleBillButtonLabel": 'Settle Bill',
    "openForDayTitle": 'Open for day',
    "daySaleTitle": 'Day Sale : ',
    "unsettledTitle": 'Unsettled : ',
    "deliveryPriceLabel": 'Delivery Price',
    "takeAwayPriceLabel": 'Take Away Price',
    "welcomeTitle": 'Welcome!',
    "subcategoryLabel": 'Sub Category',
    "subcategoriesLabel": 'Sub Categories',
    "unitLabel": 'Unit',
    "priceLabel": 'Price',
    "unitHeaderLabel": 'Unit',
    "tablePriceLabel": 'Table Price',
    "deliveryPriceLabel": 'Delivery Price',
    "takeAwayPriceLabel": 'Take Away Price',
    "tablePriceHeaderLabel": 'Table',
    "deliveryPriceHeaderLabel": 'Delivery',
    "takeAwayPriceHeaderLabel": 'Take Away',
    "openDayLabel": 'Open Day',
    "closeDayLabel": 'Close Day',
    "myProfileLabel": 'My profile',
    "logoutLabel": 'Logout',
    "supportLabel": 'Support',
    "addSubCategoryLabel": 'Add Sub Category',
    "activityLabel": 'Activity',
    "settingsLabel": 'Settings',
    "loginLabel": 'Login',
    "registerLabel": 'Register',
    "editLabel": 'Edit',
    "deleteLabel": 'Delete',
    "alreadyHaveAccount": 'Already have an account? ',
    "categoriesTitle": 'Categories',
    "paymentDueTitle": 'Payment Due',
    "discountAmountTitle": 'Discount',
    "onlinePaymentTitle": 'Online Payment',
    "codTitle": 'COD',
    "googlePayTitle": 'Google Pay',
    "phonePayTitle": 'PhonePe',
    "PaytmTitle": 'Paytm',
    "vendorLabel": 'Vendor',
    "cashTitle": 'Cash',
    "billAmountTitle": 'Bill Amount',
    "paymentTypeLabel": 'Payment Type',
    "remainingLabel": 'Remaining:',
    "tablesLabel": 'Tables',
    "tenderedLabel": 'Tendered:',
    "returnToCustomerLabel": 'Return To Customer:',
    "billDateTitle": 'Bill Date',
    "serialNoTitle": 'Sr. No.',
    "addCategoryTitle": 'Add Category',
    "discountAmountLabel": 'Discount Amount:',
    "discountPercentLabel": 'Discount (%):',
    "totalAmtLabel": 'Total Amount:',
    "totalLabel": 'Total:',
    "addCustomerLabel": 'Add Customer',
    "numberOfTablesLabel": ' Number of Tables',
    "resetPasswordTitle": 'Reset your password',
    "resetPasswordButtonTitle": 'Reset Password',
    "restaurantNameLabel": 'Restaurant Name',
    "dayOpenTimeLabel": 'Day Open Time',
    "netAmountLabel": 'Net Amount:',
    "myAccountLabel": 'My account',
    "restaurantInfoLabel": 'Restaurant information',
    "paymentDueDateLabel": 'Payment Due Date:',
    "paymentModeLabel": 'Payment Mode',
    "transactionNumberLabel": 'Transaction Number',
    "endDateLabel": 'End Date:',
    "actionLabel": 'Action',
    "anotherActionLabel": 'Another action',
    "somethingElseLabel": 'Something else here',
    "startDateLabel": 'Start Date:',
    "subscriptionDetailsLabel": 'Subscription Details',
    "subscriptionStatusLabel": 'Subscription Status: ',
    "registrationDateLabel": 'Registration Date: ',
    "amountLabel": 'Amount',
    "amountPlaceholder": 'Enter Amount',
    "addPaymentLabel": ' Add Payment',
    "taxLabel": 'Tax:',
    "addButtonLabel": 'Add',
    "nameLabel": 'Name',
    "quantityLabel": 'Quantity',
    "rateLabel": 'Rate',
    "emailLabel": 'Email address',
    "altMobileNoLabel": 'Alternate Mobile Number',
    "saveButtonLabel": 'Save',
    "gstNoLabel": 'GST Number',
    "websiteLabel": 'Website',
    "contactInfoLabel": 'Contact information',
    "cityLabel": 'City',
    "stateLabel": 'State',
    "createNewAccountLabel": 'Create new account',
    "forgotPasswordLabel": 'Forgot Password',
    "zipCodeLabel": 'Zip Code',
    "addressLabel": 'Address',
    "mobileNoLabel": 'Mobile Number',
    "customerInfoLabel": 'Customer information',
    "cancelButtonLabel": 'Cancel',
    "okButtonLabel": 'Ok',
    "freelancersLabel": 'Freelancers',
    "homeLabel": 'Home',
    "updateButtonLabel": 'Update',
    "aboutUsLabel": 'About Us',
    "contactUsLabel": 'Contact Us',
    "blogLabel": 'Blog',
    "backLabel": 'Back',
    "vegNonVegLabel": 'Veg/Non Veg',
    "backToLoginLabel": 'Back to Login',
    "rememberMeLabel": 'Remember me',
    "signInLabel": 'Sign in',
    "iAgreeTitle": 'I agree with the{" "}',
    "iAgreeLink": ' Terms and Conditions',
    "signInTitle": 'Sign in with your credentials',
    "signUpTitle": 'Sign up with credentials',
    "restaurantUpdatePolicy": 'You can update your restaurant details from here and also you can manage your subscription plan.',
    "addMenuItemLabel": 'Add Menu Item',
    "isDiscountApplicableLabel": 'Is Discount Applicable',
    "showPricingTitle": 'Pricing',
    "selectPricingTitle": 'Select Order Quantity',
    "displayForMenu": "Menu",
    "displayForOrder": "Order",
    "displayTablePrice": "Table Price",
    "displayTakeAwayPrice": "Take Away Price",
    "displayDeliveryPrice": "Delivery Price",
    "selectOrderQuantity": "Select Variant",
    "dueAmountLabel": "Due Amount",
    "settleAmountLabel": "Settle Dues",
    "settlementAmountLabel": "Amount",
    "settleBtnLabel": "Settle",
    "backBtnLabel": "Back",
    "dayBookLabel": 'Day Book',
    "openingBalanceLabel": "Opening Balance",
    "dayCreditLabel": "Total Day Credit",
    "dayDebitLabel": "Total Day Debit",
    "balanceLabel": "Day Balance",
    "closingBalanceLabel": "Closing Balance",
    "accountBookLabel": "Account Book"
}